---
train:
  params:
    batch_size: 16
    epoch: 100
    lr: 0.1
    decay: 0.1
    decay_step: 20
    loss: CrossEntropyLoss
    margin: 5.0
    lambda_triplet: 0.1
  save:
    save_path: "/home/xmj/ml-course/car/experiments/triplet-5.0-0.1"
    model_name: model
    step: 10
  data:
    image: "/home/xmj/ml-course/car/dataset"
    label: "/home/xmj/ml-course/car/dataset/train.label"
  pretrains: "None"
test:
   load:
      begin_step: 10
      end_step: 100
      steps: 10
      load_path: "/home/xmj/ml-course/car/experiments/triplet-5.0-0.1"
      model_name: model
   data:
      image: "/home/xmj/ml-course/car/dataset"
      label: "/home/xmj/ml-course/car/dataset/test.label"
reader: reader_double
reader_test: reader_test
